// Generates supabase/seed.sql from the curated fixtures in src/data so the
// database and the offline fallback never drift apart.
//
//   npm run seed:generate

import { writeFileSync } from 'node:fs';
import { CEMETERIES } from '../src/data/cemeteries';
import { PERSONS } from '../src/data/persons';
import { ROUTES } from '../src/data/routes';

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (Array.isArray(v)) return `array[${v.map(q).join(', ')}]::bigint[]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const out: string[] = [];
out.push('-- GENERATED by scripts/generate-seed.ts — do not edit by hand.');
out.push('-- Curated reference data. Idempotent: re-running upserts the same rows.');
out.push('');
out.push('begin;');
out.push('');
out.push('-- cemeteries ----------------------------------------------------------------');
for (const c of CEMETERIES) {
  out.push(
    `insert into cemeteries (id, name, city, lat, lng, description) values (${[c.id, c.name, c.city, c.lat, c.lng, c.description ?? null].map(q).join(', ')})\n` +
      '  on conflict (id) do update set name = excluded.name, city = excluded.city, lat = excluded.lat, lng = excluded.lng, description = excluded.description;',
  );
}
out.push(
  "select setval(pg_get_serial_sequence('public.cemeteries', 'id'), greatest(1000, (select max(id) from cemeteries)));",
);
out.push('');
out.push('-- persons -------------------------------------------------------------------');
const cols = [
  'id',
  'name',
  'born',
  'died',
  'birth_date',
  'death_date',
  'birth_year',
  'death_year',
  'birth_place',
  'death_place',
  'profession',
  'cemetery',
  'cemetery_id',
  'city',
  'lat',
  'lng',
  'location_precision',
  'confidence',
  'short_bio',
  'full_bio',
  'era',
  'era_years',
  'time_window_title',
  'category',
  'wikipedia_url',
  'curated',
];
for (const p of PERSONS) {
  const values = [
    p.id,
    p.name,
    p.born,
    p.died,
    p.birthDate,
    p.deathDate,
    p.birthYear,
    p.deathYear,
    p.birthPlace,
    p.deathPlace,
    p.profession,
    p.cemetery,
    p.cemeteryId,
    p.city,
    p.lat,
    p.lng,
    p.locationPrecision,
    p.confidence,
    p.shortBio,
    p.fullBio,
    p.era,
    p.eraYears,
    p.timeWindowTitle,
    p.category,
    p.wikipediaUrl,
    true,
  ];
  const updates = cols
    .filter((c) => c !== 'id')
    .map((c) => `${c} = excluded.${c}`)
    .join(', ');
  out.push(
    `insert into persons (${cols.join(', ')}) values (${values.map(q).join(', ')})\n  on conflict (id) do update set ${updates};`,
  );
  out.push(`delete from timeline_events where person_id = ${p.id};`);
  p.timeline.forEach((t, i) => {
    out.push(
      `insert into timeline_events (person_id, year, event, sort_order) values (${[p.id, t.year, t.event, i].map(q).join(', ')});`,
    );
  });
  out.push(`delete from person_sources where person_id = ${p.id};`);
  p.sources.forEach((s, i) => {
    out.push(
      `insert into person_sources (person_id, label, url, sort_order) values (${[p.id, s.label, s.url ?? null, i].map(q).join(', ')});`,
    );
  });
  out.push('');
}
out.push('-- routes --------------------------------------------------------------------');
for (const r of ROUTES) {
  out.push(
    `insert into routes (id, title, subtitle, stops, duration, distance, category, emoji, person_ids) values (${[r.id, r.title, r.subtitle, r.stops, r.duration, r.distance, r.category, r.emoji, r.personIds].map(q).join(', ')})\n` +
      '  on conflict (id) do update set title = excluded.title, subtitle = excluded.subtitle, stops = excluded.stops, duration = excluded.duration, distance = excluded.distance, category = excluded.category, emoji = excluded.emoji, person_ids = excluded.person_ids;',
  );
}
out.push('');
out.push('commit;');
out.push('');

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n'));
console.log(
  `Wrote seed.sql: ${CEMETERIES.length} cemeteries, ${PERSONS.length} persons, ${ROUTES.length} routes`,
);
