-- MindSTEN: full app schema (cemeteries, geo, fuzzy search, scan matching,
-- AI era-story cache, grave submissions, rate limiting).
-- Idempotent: safe to re-run.

create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;
create extension if not exists unaccent with schema extensions;

-- Resolve trigram operators/opclasses whether the extensions live in
-- `extensions` (Supabase default) or `public`.
set search_path = public, extensions;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- unaccent() is only STABLE; wrap it so it can be used in indexes/triggers.
create or replace function public.mindsten_normalize(input text)
returns text
language sql
immutable
parallel safe
set search_path = public, extensions
as $$
  select lower(unaccent('unaccent'::regdictionary, coalesce(input, '')))
$$;

create or replace function public.mindsten_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Cemeteries
-- ---------------------------------------------------------------------------

create table if not exists cemeteries (
  id           bigint generated by default as identity primary key,
  name         text not null,
  city         text not null default '',
  municipality text,
  lat          double precision,
  lng          double precision,
  description  text,
  wikidata_id  text unique,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists cemeteries_name_trgm_idx
  on cemeteries using gin (public.mindsten_normalize(name) gin_trgm_ops);

drop trigger if exists cemeteries_touch on cemeteries;
create trigger cemeteries_touch before update on cemeteries
  for each row execute function public.mindsten_touch_updated_at();

alter table cemeteries enable row level security;
drop policy if exists cemeteries_public_read on cemeteries;
create policy cemeteries_public_read on cemeteries for select using (true);

-- ---------------------------------------------------------------------------
-- Persons: widen the prototype table
-- ---------------------------------------------------------------------------

alter table persons drop constraint if exists persons_category_check;
alter table persons add constraint persons_category_check check (
  category in ('writers','art','music','science','thinkers','royals','naval',
               'politics','stage','sports','other')
);

alter table persons alter column born drop not null;
alter table persons alter column died drop not null;
alter table persons alter column full_bio drop not null;
alter table persons alter column full_bio set default '';
alter table persons alter column short_bio set default '';
alter table persons alter column era drop not null;
alter table persons alter column era_years drop not null;
alter table persons alter column time_window_title drop not null;
alter table persons alter column confidence set default 70;
alter table persons alter column city set default '';
alter table persons alter column profession set default '';

alter table persons add column if not exists birth_date        date;
alter table persons add column if not exists death_date        date;
alter table persons add column if not exists birth_year        int;
alter table persons add column if not exists death_year        int;
alter table persons add column if not exists birth_place       text;
alter table persons add column if not exists death_place       text;
alter table persons add column if not exists cemetery_id       bigint references cemeteries(id) on delete set null;
alter table persons add column if not exists lat               double precision;
alter table persons add column if not exists lng               double precision;
alter table persons add column if not exists location_precision text not null default 'unknown';
alter table persons add column if not exists image_url         text;
alter table persons add column if not exists image_credit      text;
alter table persons add column if not exists wikidata_id       text;
alter table persons add column if not exists wikipedia_url     text;
alter table persons add column if not exists aliases           text[] not null default '{}';
alter table persons add column if not exists search_name       text not null default '';
alter table persons add column if not exists curated           boolean not null default false;

alter table persons drop constraint if exists persons_location_precision_check;
alter table persons add constraint persons_location_precision_check
  check (location_precision in ('grave','cemetery','unknown'));

create unique index if not exists persons_wikidata_id_key on persons (wikidata_id);
create index if not exists persons_search_trgm_idx on persons using gin (search_name gin_trgm_ops);
create index if not exists persons_lat_lng_idx on persons (lat, lng);
create index if not exists persons_years_idx on persons (death_year, birth_year);
create index if not exists persons_cemetery_id_idx on persons (cemetery_id);

-- Identity for new (imported) rows. Curated rows keep ids < 1000.
do $$
begin
  if not exists (
    select 1 from pg_attribute
    where attrelid = 'public.persons'::regclass and attname = 'id' and attidentity <> ''
  ) then
    alter table persons alter column id add generated by default as identity;
    perform setval(
      pg_get_serial_sequence('public.persons', 'id'),
      greatest(1000, (select coalesce(max(id), 0) + 1 from persons)),
      false
    );
  end if;
end;
$$;

create or replace function public.mindsten_persons_before_write()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.search_name := public.mindsten_normalize(
    new.name || ' ' || array_to_string(coalesce(new.aliases, '{}'), ' ')
  );
  if new.birth_year is null and new.birth_date is not null then
    new.birth_year := extract(year from new.birth_date)::int;
  end if;
  if new.death_year is null and new.death_date is not null then
    new.death_year := extract(year from new.death_date)::int;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists persons_before_write on persons;
create trigger persons_before_write before insert or update on persons
  for each row execute function public.mindsten_persons_before_write();

-- Backfill search_name for rows that existed before this migration.
update persons set name = name where search_name = '';

-- ---------------------------------------------------------------------------
-- Routes
-- ---------------------------------------------------------------------------

alter table routes drop constraint if exists routes_category_check;
alter table routes add constraint routes_category_check check (
  category in ('writers','art','music','science','thinkers','royals','naval',
               'politics','stage','sports','other')
);
alter table routes add column if not exists person_ids bigint[] not null default '{}';

-- ---------------------------------------------------------------------------
-- Timeline/sources: allow URLs on sources (already present) — nothing to do.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- AI era stories (cache, written only by the era-story Edge Function)
-- ---------------------------------------------------------------------------

create table if not exists era_stories (
  person_id  bigint primary key references persons(id) on delete cascade,
  content    jsonb not null,
  model      text,
  created_at timestamptz not null default now()
);

alter table era_stories enable row level security;
drop policy if exists era_stories_public_read on era_stories;
create policy era_stories_public_read on era_stories for select using (true);

-- ---------------------------------------------------------------------------
-- Grave submissions from users ("Tilføj en grav")
-- ---------------------------------------------------------------------------

create table if not exists grave_submissions (
  id          uuid primary key default gen_random_uuid(),
  name        text not null check (char_length(name) between 2 and 200),
  birth_year  int check (birth_year between 800 and 2100),
  death_year  int check (death_year between 800 and 2100),
  cemetery    text not null default '' check (char_length(cemetery) <= 200),
  lat         double precision check (lat between -90 and 90),
  lng         double precision check (lng between -180 and 180),
  note        text not null default '' check (char_length(note) <= 2000),
  status      text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at  timestamptz not null default now()
);

alter table grave_submissions enable row level security;
drop policy if exists grave_submissions_anon_insert on grave_submissions;
create policy grave_submissions_anon_insert on grave_submissions
  for insert to anon, authenticated
  with check (status = 'pending');
-- No select policy: submissions are only visible with the service role.

-- ---------------------------------------------------------------------------
-- Rate limiting for Edge Functions (service role only)
-- ---------------------------------------------------------------------------

create table if not exists rate_limits (
  bucket       text not null,
  window_start timestamptz not null,
  hits         int not null default 0,
  primary key (bucket, window_start)
);
alter table rate_limits enable row level security;

create or replace function public.mindsten_bump_rate_limit(
  p_bucket text, p_limit int, p_window_seconds int
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_window timestamptz := to_timestamp(
    floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds
  );
  v_hits int;
begin
  insert into rate_limits (bucket, window_start, hits)
  values (p_bucket, v_window, 1)
  on conflict (bucket, window_start) do update set hits = rate_limits.hits + 1
  returning hits into v_hits;
  delete from rate_limits where window_start < now() - interval '2 days';
  return v_hits <= p_limit;
end;
$$;

revoke all on function public.mindsten_bump_rate_limit(text, int, int) from public, anon, authenticated;
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant execute on function public.mindsten_bump_rate_limit(text, int, int) to service_role;
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- Query functions (called via supabase.rpc)
-- ---------------------------------------------------------------------------

create or replace function public.mindsten_distance_m(
  lat1 double precision, lng1 double precision, lat2 double precision, lng2 double precision
) returns double precision
language sql
immutable
parallel safe
as $$
  select 2 * 6371000 * asin(sqrt(
    power(sin(radians(lat2 - lat1) / 2), 2) +
    cos(radians(lat1)) * cos(radians(lat2)) * power(sin(radians(lng2 - lng1) / 2), 2)
  ))
$$;

create or replace function public.nearby_persons(
  p_lat double precision,
  p_lng double precision,
  p_radius_m double precision default 5000,
  p_limit int default 20
) returns table (person_id bigint, distance_m double precision)
language sql
stable
set search_path = public
as $$
  select p.id, public.mindsten_distance_m(p_lat, p_lng, p.lat, p.lng) as d
  from persons p
  where p.lat is not null and p.lng is not null
    -- cheap bounding box before the exact distance
    and p.lat between p_lat - (p_radius_m / 111000.0) and p_lat + (p_radius_m / 111000.0)
    and p.lng between p_lng - (p_radius_m / (111000.0 * greatest(cos(radians(p_lat)), 0.01)))
                  and p_lng + (p_radius_m / (111000.0 * greatest(cos(radians(p_lat)), 0.01)))
    and public.mindsten_distance_m(p_lat, p_lng, p.lat, p.lng) <= p_radius_m
  order by d asc, p.curated desc, p.id
  limit least(greatest(p_limit, 1), 200)
$$;

create or replace function public.search_persons(
  p_query text,
  p_limit int default 20
) returns table (person_id bigint, score real)
language sql
stable
set search_path = public, extensions
as $$
  with q as (select public.mindsten_normalize(p_query) as v)
  select p.id,
         greatest(word_similarity(q.v, p.search_name),
                  case when p.search_name like '%' || q.v || '%' then 1.0 else 0 end)::real as s
  from persons p, q
  where char_length(q.v) >= 2
    and (p.search_name like '%' || q.v || '%' or q.v <% p.search_name)
  order by s desc, p.curated desc, p.death_year desc nulls last
  limit least(greatest(p_limit, 1), 100)
$$;

-- Ranks persons against what was read off a gravestone.
-- score 0–100: name 0–60, years 0–30, distance 0–10.
create or replace function public.match_gravestone(
  p_names text[],
  p_birth_year int default null,
  p_death_year int default null,
  p_lat double precision default null,
  p_lng double precision default null,
  p_limit int default 5
) returns table (person_id bigint, score int, distance_m double precision)
language sql
stable
set search_path = public, extensions
as $$
  with names as (
    select public.mindsten_normalize(n) as v
    from unnest(coalesce(p_names, '{}')) as n
    where char_length(trim(n)) >= 2
  ),
  scored as (
    select p.id,
      coalesce((select max(word_similarity(names.v, p.search_name)) from names), 0) as name_sim,
      case
        when p_birth_year is null or p.birth_year is null then 0
        when p.birth_year = p_birth_year then 15
        when abs(p.birth_year - p_birth_year) = 1 then 8
        else -10
      end +
      case
        when p_death_year is null or p.death_year is null then 0
        when p.death_year = p_death_year then 15
        when abs(p.death_year - p_death_year) = 1 then 8
        else -10
      end as year_pts,
      case
        when p_lat is null or p_lng is null or p.lat is null or p.lng is null then null
        else public.mindsten_distance_m(p_lat, p_lng, p.lat, p.lng)
      end as dist
    from persons p
    where exists (select 1 from names where names.v <% p.search_name or p.search_name like '%' || names.v || '%')
       or (p_death_year is not null and p.death_year = p_death_year
           and p_birth_year is not null and p.birth_year = p_birth_year)
  )
  select id,
    greatest(0, least(100, round(
      name_sim * 60 + year_pts +
      case when dist is null then 0 when dist < 300 then 10 when dist < 3000 then 5 else 0 end
    )))::int as score,
    dist
  from scored
  order by score desc, dist asc nulls last
  limit least(greatest(p_limit, 1), 20)
$$;

grant execute on function public.nearby_persons(double precision, double precision, double precision, int) to anon, authenticated;
grant execute on function public.search_persons(text, int) to anon, authenticated;
grant execute on function public.match_gravestone(text[], int, int, double precision, double precision, int) to anon, authenticated;
